    /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package multitodo1.vista.Gerente;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Paint;
import java.util.Random;
import javax.swing.JOptionPane;
import org.w3c.dom.css.RGBColor;

/**
 *
 * @author ferna
 */
public class Estadisticas extends javax.swing.JDialog {
    
   
    
   multitodo1.modelo.Gerente ger = new multitodo1.modelo.Gerente();
   
   boolean bandera = false;
   
    /**
     * Creates new form Estadisticas
     */
    public Estadisticas(java.awt.Frame parent, boolean modal) {
         super(parent, modal);
        initComponents();
        
    }
 
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("GRAFICA CIRCULAR");

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(285, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         bandera = true;
        repaint();
        
       
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Estadisticas dialog = new Estadisticas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables





   @Override
   public void paint(Graphics g){
    
       super.paint(g);
       
       if(bandera == true){
       int total_dep = ger.Total_dep();
       
     
       int departamentos[] = new int[total_dep];
       String nom_dep[] = new String[total_dep];
       int valor_total = 0;
       
       
       int i = 0;
       
       int id = 0;
       
       while(i != total_dep){
           
           
           int cant = ger.get_cant_x_departamento(id);
           
           if(cant != 0){
               
               departamentos[i] = cant;
               nom_dep[i] = ger.getDepartamento(id);
               valor_total += departamentos[i];
               i++;
               
           }
           
           id++;
       }
       
       int grados[] = new int[total_dep]; 
       
       for(int j = 0; j < departamentos.length; j++){
           
           grados[j] = departamentos[j] * 360 / valor_total;
           
           
       }
       
       
       int inicio = 0;
       
       Random aleatorio = new Random();
       
       
       
       int total_grados = 0;
       
            
           
       for(int k = 0; k < departamentos.length; k++ ){
            int rojo = aleatorio.nextInt(256);
           int azul = aleatorio.nextInt(256);
           int verde = aleatorio.nextInt(256);
      
           if(inicio == 0){
              g.setColor(new Color(rojo,verde,azul));
               g.fillArc(100, 100, 200, 200, 0, grados[k]);
               g.fillRect(310, 250, 10, 10);
               
               double calculo = ((double) departamentos[k] / (double) valor_total) * 100;
               
               String porcentaje;
               if(calculo % 1 == 0){
                   
                   porcentaje = String.format("%.0f", calculo);
               }else{
                   porcentaje = String.format("%.2f",calculo);
               }
               g.setColor(Color.BLACK);
               g.drawString(nom_dep[k] + "  "   + porcentaje + "%", 320, 260);
               
               total_grados += grados[k];
               inicio = 1;
               
           }else{
               g.setColor(new Color(rojo,verde,azul));
               g.fillArc(100, 100, 200, 200, total_grados, grados[k]);
               g.fillRect(310, 250 + (k*50),10, 10);
               double calculo = ((double) departamentos[k] / (double) valor_total) * 100;
                String porcentaje;
               if(calculo % 1 == 0){
                   
                   porcentaje = String.format("%.0f", calculo);
               }else{
                   porcentaje = String.format("%.2f",calculo);
               }
               
               g.setColor(Color.BLACK);
               g.drawString(nom_dep[k] + " " + porcentaje  + "%", 320, 260 + (k*50));
               total_grados += grados[k];
           }
           
           
           
           
           
       }
           
           
           
       }
       
       
       
           
       
}






}

